package com.forumx.platform.tenant.service.impl;

import com.forumx.auth.invitation.repository.ModeratorInvitationRepository;
import com.forumx.auth.repository.RefreshTokenRepository;
import com.forumx.platform.invitation.repository.TenantAdminInvitationRepository;
import com.forumx.common.exception.TenantSlugAlreadyExistsException;
import com.forumx.platform.tenant.dto.CreateTenantRequest;
import com.forumx.platform.tenant.dto.TenantResponse;
import com.forumx.platform.tenant.service.PlatformTenantService;
import com.forumx.tenant.entity.Tenant;
import com.forumx.tenant.repository.TenantRepository;
import com.forumx.tenant.util.TenantSlugProvisioner;
import jakarta.persistence.EntityNotFoundException;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.Instant;

@Slf4j
@Service
@RequiredArgsConstructor
public class PlatformTenantServiceImpl implements PlatformTenantService {

    private final TenantRepository tenantRepository;
    private final RefreshTokenRepository refreshTokenRepository;
    private final ModeratorInvitationRepository moderatorInvitationRepository;
    private final TenantAdminInvitationRepository tenantAdminInvitationRepository;
    private final TenantSlugProvisioner tenantSlugProvisioner;

    @Value("${app.frontend.base-url:http://localhost:5173}")
    private String frontendBaseUrl;

    @Override
    @Transactional
    public TenantResponse createTenant(CreateTenantRequest request) {
        Tenant.SubscriptionPlan plan = Tenant.SubscriptionPlan.FREE;
        if (request.getSubscriptionPlan() != null && !request.getSubscriptionPlan().isBlank()) {
            try {
                plan = Tenant.SubscriptionPlan.valueOf(request.getSubscriptionPlan().toUpperCase());
            } catch (IllegalArgumentException e) {
                log.warn("Unknown subscription plan '{}', falling back to FREE", request.getSubscriptionPlan());
            }
        }

        Tenant saved;
        if (request.getSlug() != null && !request.getSlug().isBlank()) {
            // Manual slug provisioning — strict validation & no silent auto-suffixing
            String manualSlug = tenantSlugProvisioner.validateAndNormalizeManualSlug(request.getSlug());
            Tenant tenant = buildTenantEntity(request, manualSlug, plan);
            try {
                saved = tenantRepository.saveAndFlush(tenant);
            } catch (DataIntegrityViolationException e) {
                if (isSlugConstraintViolation(e)) {
                    log.warn("Concurrent slug collision for manual slug: {}", manualSlug);
                    throw new TenantSlugAlreadyExistsException("Tenant with slug '" + manualSlug + "' already exists");
                }
                throw e;
            }
        } else {
            // Auto-generated slug provisioning with concurrency retry resilience
            saved = null;
            for (int attempt = 0; attempt < 5; attempt++) {
                String candidateSlug = tenantSlugProvisioner.provisionAutoGeneratedSlug(request.getName(), attempt);
                Tenant tenant = buildTenantEntity(request, candidateSlug, plan);
                try {
                    saved = tenantRepository.saveAndFlush(tenant);
                    break;
                } catch (DataIntegrityViolationException e) {
                    if (isSlugConstraintViolation(e)) {
                        log.warn("Concurrent slug collision on '{}' (attempt={}), retrying with next suffix",
                                candidateSlug, attempt);
                    } else {
                        throw e;
                    }
                }
            }
            if (saved == null) {
                throw new IllegalStateException("Failed to provision a unique tenant slug after multiple attempts");
            }
        }

        log.info("PLATFORM_TENANT_CREATED tenantId={} slug={}", saved.getId(), saved.getSlug());
        return mapToResponse(saved);
    }

    private boolean isSlugConstraintViolation(DataIntegrityViolationException e) {
        String msg = e.getMessage() != null ? e.getMessage() : "";
        Throwable root = e.getRootCause();
        if (root != null && root.getMessage() != null) {
            msg = msg + " " + root.getMessage();
        }
        return msg.contains("uk_tenants_slug") || msg.toLowerCase().contains("slug");
    }

    private Tenant buildTenantEntity(CreateTenantRequest request, String slug, Tenant.SubscriptionPlan plan) {
        return Tenant.builder()
                .name(request.getName().trim())
                .slug(slug)
                .status(Tenant.TenantStatus.ACTIVE)
                .subscriptionPlan(plan)
                .maxUsers(request.getMaxUsers() != null ? request.getMaxUsers() : 100)
                .storageQuotaMB(request.getStorageQuotaMB() != null ? request.getStorageQuotaMB() : 1024L)
                .timezone(request.getTimezone() != null ? request.getTimezone() : "UTC")
                .locale(request.getLocale() != null ? request.getLocale() : "en_US")
                .build();
    }

    @Override
    @Transactional(readOnly = true)
    public Page<TenantResponse> listTenants(Pageable pageable) {
        return tenantRepository.findAll(pageable).map(this::mapToResponse);
    }

    @Override
    @Transactional(readOnly = true)
    public TenantResponse getTenant(Long tenantId) {
        Tenant tenant = tenantRepository.findByIdAndDeletedFalse(tenantId)
                .orElseThrow(() -> new EntityNotFoundException("Tenant not found with ID: " + tenantId));
        return mapToResponse(tenant);
    }

    /**
     * Safely deactivates a tenant:
     * <ol>
     *   <li>Loads only a currently active, non-deleted tenant.</li>
     *   <li>Marks it INACTIVE and applies soft-delete semantics.</li>
     *   <li>Revokes all active user refresh tokens (bulk — single UPDATE).</li>
     *   <li>Revokes all outstanding PENDING invitations (moderator + tenant admin).</li>
     * </ol>
     * All steps run within a single transaction so a mid-flight failure rolls back entirely.
     *
     * @param tenantId the ID of the tenant to deactivate
     * @throws EntityNotFoundException if the tenant does not exist or is already deactivated/deleted
     */
    @Override
    @Transactional
    public void deactivateTenant(Long tenantId) {
        Tenant tenant = tenantRepository.findByIdAndDeletedFalse(tenantId)
                .orElseThrow(() -> new EntityNotFoundException("Tenant not found with ID: " + tenantId));

        if (!tenant.isActive()) {
            // Already inactive — idempotent: treat as success rather than error
            log.info("PLATFORM_TENANT_DEACTIVATE_NOOP tenantId={} status={} (already inactive)",
                    tenantId, tenant.getStatus());
            return;
        }

        // 1. Mark tenant INACTIVE + soft-delete
        tenant.deactivate();           // sets status = INACTIVE
        tenant.setDeleted(true);
        tenant.setDeletedAt(Instant.now());
        tenantRepository.save(tenant);

        // 2. Revoke all active refresh tokens for users of this tenant (single UPDATE)
        refreshTokenRepository.revokeAllByTenantId(tenantId);

        // 3. Revoke all outstanding PENDING moderator invitations for this tenant
        moderatorInvitationRepository.revokeAllPendingByTenantId(tenantId);

        // 4. Revoke all outstanding PENDING tenant admin invitations for this tenant
        tenantAdminInvitationRepository.revokeAllPendingByTenantId(tenantId);

        log.info("PLATFORM_TENANT_DEACTIVATED tenantId={} slug={}", tenantId, tenant.getSlug());
    }

    private TenantResponse mapToResponse(Tenant tenant) {
        String cleanBaseUrl = (frontendBaseUrl != null && !frontendBaseUrl.isBlank())
                ? frontendBaseUrl.trim().replaceAll("/+$", "")
                : "http://localhost:5173";
        String accessUrl = cleanBaseUrl + "/" + tenant.getSlug();

        return TenantResponse.builder()
                .id(tenant.getId())
                .name(tenant.getName())
                .slug(tenant.getSlug())
                .status(tenant.getStatus())
                .subscriptionPlan(tenant.getSubscriptionPlan())
                .maxUsers(tenant.getMaxUsers())
                .storageQuotaMB(tenant.getStorageQuotaMB())
                .timezone(tenant.getTimezone())
                .locale(tenant.getLocale())
                .accessUrl(accessUrl)
                .createdAt(tenant.getCreatedAt())
                .build();
    }
}
