package com.forumx.notification.preference.domain;

public enum DecisionReason {
    CRITICAL_TRANSACTIONAL_EMAIL_FORCED,
    USER_ONLINE_WEBSOCKET_ENABLED,
    USER_ONLINE_FALLBACK_TO_EMAIL,
    USER_OFFLINE_EMAIL_ENABLED,
    USER_OFFLINE_WEBSOCKET_DISABLED,
    PREFERENCE_DISABLED,
    PUSH_ENABLED,
    DIGEST_ENABLED
}
