package com.forumx.tenant.util;

import com.forumx.common.exception.InvalidTenantSlugException;
import com.forumx.common.exception.ReservedTenantSlugException;
import com.forumx.common.exception.TenantSlugAlreadyExistsException;
import com.forumx.tenant.repository.TenantRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

import java.util.Locale;
import java.util.Set;
import java.util.regex.Pattern;

/**
 * Reusable utility and service component for normalizing, validating, generating,
 * and provisioning unique, URL-safe tenant slugs.
 */
@Slf4j
@Component
@RequiredArgsConstructor
public class TenantSlugProvisioner {

    private final TenantRepository tenantRepository;

    private static final Pattern VALID_SLUG_PATTERN = Pattern.compile("^[a-z0-9]+(?:-[a-z0-9]+)*$");

    public static final Set<String> RESERVED_SLUGS = Set.of(
            "platform",
            "admin",
            "api",
            "auth",
            "ws",
            "actuator",
            "swagger",
            "swagger-ui",
            "v3",
            "verify-email",
            "reset-password",
            "forgot-password",
            "accept-invitation",
            "accept-admin-invitation",
            "accept-tenant-admin-invitation",
            "dashboard",
            "questions",
            "saved",
            "archived",
            "profile",
            "notifications",
            "support",
            "moderator",
            "default"
    );

    /**
     * Normalizes and strictly validates a manually provided slug.
     *
     * @param rawSlug the user-supplied slug
     * @return the normalized lowercase slug
     * @throws InvalidTenantSlugException if format or length is invalid
     * @throws ReservedTenantSlugException if slug is a reserved system path
     * @throws TenantSlugAlreadyExistsException if slug already exists in database
     */
    public String validateAndNormalizeManualSlug(String rawSlug) {
        if (rawSlug == null || rawSlug.isBlank()) {
            throw new InvalidTenantSlugException("Tenant slug cannot be blank");
        }

        String normalized = rawSlug.trim().toLowerCase(Locale.ROOT);

        if (normalized.length() < 2 || normalized.length() > 50) {
            throw new InvalidTenantSlugException("Tenant slug must be between 2 and 50 characters");
        }

        if (!VALID_SLUG_PATTERN.matcher(normalized).matches()) {
            throw new InvalidTenantSlugException("Slug must contain only lowercase alphanumeric characters and hyphens");
        }

        if (isReserved(normalized)) {
            throw new ReservedTenantSlugException("Tenant slug '" + normalized + "' is reserved and cannot be used");
        }

        if (tenantRepository.existsBySlug(normalized)) {
            throw new TenantSlugAlreadyExistsException("Tenant with slug '" + normalized + "' already exists");
        }

        return normalized;
    }

    /**
     * Automatically provisions a unique, safe slug for a tenant based on its display name.
     * Probes numeric suffixes if base slug is reserved or already taken.
     *
     * @param name the tenant display name
     * @param attemptOffset initial attempt offset (0 for base slug)
     * @return an unreserved, available slug candidate
     */
    public String provisionAutoGeneratedSlug(String name, int attemptOffset) {
        String baseSlug = sanitizeNameToBaseSlug(name);

        for (int i = attemptOffset; i < attemptOffset + 1000; i++) {
            String candidate = (i == 0) ? baseSlug : baseSlug + "-" + i;
            if (!isReserved(candidate) && !tenantRepository.existsBySlug(candidate)) {
                return candidate;
            }
        }

        return (attemptOffset == 0) ? baseSlug : baseSlug + "-" + attemptOffset;
    }

    /**
     * Converts a display name into a clean base slug.
     */
    public String sanitizeNameToBaseSlug(String name) {
        if (name == null || name.isBlank()) {
            return "tenant";
        }

        String cleaned = name.trim().toLowerCase(Locale.ROOT);
        cleaned = cleaned.replaceAll("[^a-z0-9]+", "-");
        cleaned = cleaned.replaceAll("^-+|-+$", "");

        if (cleaned.isBlank()) {
            cleaned = "tenant";
        }

        if (cleaned.length() > 40) {
            cleaned = cleaned.substring(0, 40).replaceAll("-+$", "");
        }

        return cleaned;
    }

    /**
     * Checks if the slug matches any reserved route or system keyword.
     */
    public boolean isReserved(String slug) {
        if (slug == null) {
            return false;
        }
        return RESERVED_SLUGS.contains(slug.trim().toLowerCase(Locale.ROOT));
    }
}
