-- Flyway Migration: V13__create_questions
-- Description: Create the questions table and associated indexes/constraints if they do not exist.

CREATE TABLE IF NOT EXISTS questions (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id         BIGINT NOT NULL,
    author_id         BIGINT NOT NULL,
    title             VARCHAR(255) NOT NULL,
    content           TEXT NOT NULL,
    status            VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    view_count        INTEGER NOT NULL DEFAULT 0,
    answer_count      INTEGER NOT NULL DEFAULT 0,
    vote_score        INTEGER NOT NULL DEFAULT 0,
    pinned            BOOLEAN NOT NULL DEFAULT FALSE,
    locked            BOOLEAN NOT NULL DEFAULT FALSE,
    created_at        TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at        TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_by        VARCHAR(255),
    updated_by        VARCHAR(255),
    version           BIGINT NOT NULL,
    deleted           BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at        TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT pk_questions PRIMARY KEY (id),
    CONSTRAINT fk_questions_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_questions_author FOREIGN KEY (author_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_questions_tenant ON questions (tenant_id);
CREATE INDEX IF NOT EXISTS idx_questions_author ON questions (author_id);
CREATE INDEX IF NOT EXISTS idx_questions_status ON questions (status);
CREATE INDEX IF NOT EXISTS idx_questions_deleted ON questions (deleted);
CREATE INDEX IF NOT EXISTS idx_questions_tenant_status ON questions (tenant_id, status);
