-- Flyway Migration: V14__create_answers
-- Description: Create the answers table and associated indexes/constraints.

CREATE TABLE IF NOT EXISTS answers (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id         BIGINT NOT NULL,
    question_id       BIGINT NOT NULL,
    author_id         BIGINT NOT NULL,
    content           TEXT NOT NULL,
    created_at        TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at        TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_by        VARCHAR(255),
    updated_by        VARCHAR(255),
    version           BIGINT NOT NULL,
    deleted           BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at        TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT pk_answers PRIMARY KEY (id),
    CONSTRAINT fk_answers_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_answers_question FOREIGN KEY (question_id) REFERENCES questions(id),
    CONSTRAINT fk_answers_author FOREIGN KEY (author_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_answers_tenant ON answers (tenant_id);
CREATE INDEX IF NOT EXISTS idx_answers_question ON answers (question_id);
CREATE INDEX IF NOT EXISTS idx_answers_author ON answers (author_id);
CREATE INDEX IF NOT EXISTS idx_answers_created_at ON answers (created_at);
CREATE INDEX IF NOT EXISTS idx_answers_deleted ON answers (deleted);
