CREATE TABLE IF NOT EXISTS tickets (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id         BIGINT NOT NULL,
    created_by        BIGINT NOT NULL,
    subject           VARCHAR(255) NOT NULL,
    description       TEXT NOT NULL,
    status            VARCHAR(30) NOT NULL,
    priority          VARCHAR(30) NOT NULL,
    assigned_to       BIGINT,
    last_message_at   TIMESTAMP(6) WITHOUT TIME ZONE,
    resolved_at       TIMESTAMP(6) WITHOUT TIME ZONE,
    closed_at         TIMESTAMP(6) WITHOUT TIME ZONE,
    audit_created_by  VARCHAR(255),
    updated_by        VARCHAR(255),
    version           BIGINT NOT NULL,
    created_at        TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at        TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    deleted           BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at        TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT pk_tickets PRIMARY KEY (id),
    CONSTRAINT fk_tickets_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_tickets_creator FOREIGN KEY (created_by) REFERENCES users(id),
    CONSTRAINT fk_tickets_assignee FOREIGN KEY (assigned_to) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_tickets_tenant ON tickets (tenant_id);
CREATE INDEX IF NOT EXISTS idx_tickets_created_by ON tickets (created_by);
CREATE INDEX IF NOT EXISTS idx_tickets_assigned_to ON tickets (assigned_to);
CREATE INDEX IF NOT EXISTS idx_tickets_status ON tickets (status);
CREATE INDEX IF NOT EXISTS idx_tickets_priority ON tickets (priority);
