CREATE TABLE IF NOT EXISTS ticket_messages (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ticket_id         BIGINT NOT NULL,
    sender_id         BIGINT NOT NULL,
    message           TEXT NOT NULL,
    internal_note     BOOLEAN NOT NULL DEFAULT FALSE,
    message_uuid      UUID NOT NULL,
    audit_created_by  VARCHAR(255),
    updated_by        VARCHAR(255),
    version           BIGINT NOT NULL,
    created_at        TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at        TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    deleted           BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at        TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT pk_ticket_messages PRIMARY KEY (id),
    CONSTRAINT fk_ticket_messages_ticket FOREIGN KEY (ticket_id) REFERENCES tickets(id),
    CONSTRAINT fk_ticket_messages_sender FOREIGN KEY (sender_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_ticket_messages_ticket ON ticket_messages (ticket_id);
CREATE INDEX IF NOT EXISTS idx_ticket_messages_sender ON ticket_messages (sender_id);
CREATE INDEX IF NOT EXISTS idx_ticket_messages_ticket_created ON ticket_messages (ticket_id, created_at);
CREATE UNIQUE INDEX IF NOT EXISTS idx_ticket_messages_uuid ON ticket_messages (message_uuid);
