CREATE TABLE votes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    question_id BIGINT,
    answer_id BIGINT,
    comment_id BIGINT,
    voter_id BIGINT NOT NULL,
    vote_type VARCHAR(10) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    version BIGINT NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT pk_votes PRIMARY KEY (id),
    CONSTRAINT fk_votes_question FOREIGN KEY (question_id) REFERENCES questions(id),
    CONSTRAINT fk_votes_answer FOREIGN KEY (answer_id) REFERENCES answers(id),
    CONSTRAINT fk_votes_comment FOREIGN KEY (comment_id) REFERENCES comments(id),
    CONSTRAINT fk_votes_voter FOREIGN KEY (voter_id) REFERENCES users(id),
    CONSTRAINT ck_votes_one_target CHECK (
        (CASE WHEN question_id IS NULL THEN 0 ELSE 1 END) +
        (CASE WHEN answer_id IS NULL THEN 0 ELSE 1 END) +
        (CASE WHEN comment_id IS NULL THEN 0 ELSE 1 END) = 1
    ),
    CONSTRAINT uk_votes_question_voter UNIQUE (question_id, voter_id),
    CONSTRAINT uk_votes_answer_voter UNIQUE (answer_id, voter_id),
    CONSTRAINT uk_votes_comment_voter UNIQUE (comment_id, voter_id)
);
CREATE INDEX idx_votes_question ON votes (question_id);
CREATE INDEX idx_votes_answer ON votes (answer_id);
CREATE INDEX idx_votes_comment ON votes (comment_id);
CREATE INDEX idx_votes_voter ON votes (voter_id);
