CREATE TABLE reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id BIGINT NOT NULL,
    question_id BIGINT,
    answer_id BIGINT,
    comment_id BIGINT,
    reporter_id BIGINT NOT NULL,
    reason VARCHAR(50) NOT NULL,
    description VARCHAR(1000),
    status VARCHAR(50) NOT NULL,
    resolved_by BIGINT,
    resolved_at TIMESTAMP(6) WITH TIME ZONE,
    resolution_note VARCHAR(1000),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMP(6) WITH TIME ZONE,
    version BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    CONSTRAINT pk_reports PRIMARY KEY (id),
    CONSTRAINT fk_reports_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_reports_question FOREIGN KEY (question_id) REFERENCES questions(id),
    CONSTRAINT fk_reports_answer FOREIGN KEY (answer_id) REFERENCES answers(id),
    CONSTRAINT fk_reports_comment FOREIGN KEY (comment_id) REFERENCES comments(id),
    CONSTRAINT fk_reports_reporter FOREIGN KEY (reporter_id) REFERENCES users(id),
    CONSTRAINT ck_reports_one_target CHECK (
        (CASE WHEN question_id IS NULL THEN 0 ELSE 1 END) +
        (CASE WHEN answer_id IS NULL THEN 0 ELSE 1 END) +
        (CASE WHEN comment_id IS NULL THEN 0 ELSE 1 END) = 1
    )
);

CREATE INDEX idx_reports_tenant ON reports (tenant_id);
CREATE INDEX idx_reports_question ON reports (question_id);
CREATE INDEX idx_reports_answer ON reports (answer_id);
CREATE INDEX idx_reports_comment ON reports (comment_id);
CREATE INDEX idx_reports_reporter ON reports (reporter_id);
CREATE INDEX idx_reports_status ON reports (status);

-- Partial unique constraints: One active (status = 'OPEN' and deleted = false) report per user per target.
CREATE UNIQUE INDEX uk_reports_question_reporter ON reports (question_id, reporter_id) WHERE (status = 'OPEN' AND deleted = false);
CREATE UNIQUE INDEX uk_reports_answer_reporter ON reports (answer_id, reporter_id) WHERE (status = 'OPEN' AND deleted = false);
CREATE UNIQUE INDEX uk_reports_comment_reporter ON reports (comment_id, reporter_id) WHERE (status = 'OPEN' AND deleted = false);
