CREATE TABLE bookmarks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    question_id BIGINT NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMP(6) WITH TIME ZONE,
    version BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    CONSTRAINT pk_bookmarks PRIMARY KEY (id),
    CONSTRAINT fk_bookmarks_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_bookmarks_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_bookmarks_question FOREIGN KEY (question_id) REFERENCES questions(id)
);

CREATE INDEX idx_bookmarks_tenant ON bookmarks (tenant_id);
CREATE INDEX idx_bookmarks_user ON bookmarks (user_id);
CREATE INDEX idx_bookmarks_question ON bookmarks (question_id);
CREATE INDEX idx_bookmarks_user_deleted ON bookmarks (user_id, deleted);

-- Ensure only one active bookmark exists per user per question
CREATE UNIQUE INDEX uk_bookmarks_user_question ON bookmarks (user_id, question_id) WHERE (deleted = false);
