CREATE TABLE IF NOT EXISTS chat_sessions (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ticket_id    BIGINT NOT NULL,
    tenant_id    BIGINT NOT NULL,
    customer_id  BIGINT NOT NULL,
    moderator_id BIGINT NOT NULL,
    status       VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    created_by   VARCHAR(255),
    updated_by   VARCHAR(255),
    version      BIGINT NOT NULL,
    created_at   TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at   TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    deleted      BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at   TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT pk_chat_sessions           PRIMARY KEY (id),
    CONSTRAINT fk_chat_sessions_ticket    FOREIGN KEY (ticket_id)    REFERENCES tickets(id),
    CONSTRAINT fk_chat_sessions_tenant    FOREIGN KEY (tenant_id)    REFERENCES tenants(id),
    CONSTRAINT fk_chat_sessions_customer  FOREIGN KEY (customer_id)  REFERENCES users(id),
    CONSTRAINT fk_chat_sessions_moderator FOREIGN KEY (moderator_id) REFERENCES users(id),
    CONSTRAINT uq_chat_sessions_ticket    UNIQUE (ticket_id)
);

CREATE TABLE IF NOT EXISTS chat_messages (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    session_id      BIGINT NOT NULL,
    sender_id       BIGINT NOT NULL,
    message_type    VARCHAR(30) NOT NULL DEFAULT 'TEXT',
    content         TEXT NOT NULL,
    delivery_status VARCHAR(30) NOT NULL DEFAULT 'SENT',
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255),
    version         BIGINT NOT NULL,
    created_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    deleted         BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at      TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT pk_chat_messages          PRIMARY KEY (id),
    CONSTRAINT fk_chat_messages_session  FOREIGN KEY (session_id) REFERENCES chat_sessions(id),
    CONSTRAINT fk_chat_messages_sender   FOREIGN KEY (sender_id)  REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_chat_sessions_ticket  ON chat_sessions (ticket_id);
CREATE INDEX IF NOT EXISTS idx_chat_sessions_tenant  ON chat_sessions (tenant_id);
CREATE INDEX IF NOT EXISTS idx_chat_messages_session ON chat_messages (session_id);
CREATE INDEX IF NOT EXISTS idx_chat_messages_sender  ON chat_messages (sender_id);
-- Covers ORDER BY created_at ASC, id ASC and cursor WHERE id < :beforeMessageId
CREATE INDEX IF NOT EXISTS idx_chat_messages_cursor
    ON chat_messages (session_id, created_at ASC, id ASC);
