CREATE TABLE IF NOT EXISTS notification_preferences (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id         BIGINT NOT NULL,
    user_id           BIGINT NOT NULL,
    notification_type VARCHAR(50) NOT NULL,
    email_enabled     BOOLEAN NOT NULL DEFAULT TRUE,
    websocket_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    push_enabled      BOOLEAN NOT NULL DEFAULT FALSE,
    digest_enabled    BOOLEAN NOT NULL DEFAULT FALSE,
    created_at        TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at        TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_by        VARCHAR(255),
    updated_by        VARCHAR(255),
    version           BIGINT NOT NULL DEFAULT 0,
    deleted           BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at        TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT pk_notification_preferences PRIMARY KEY (id),
    CONSTRAINT fk_notif_pref_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_notif_pref_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT uk_user_notification_type UNIQUE (user_id, notification_type)
);

CREATE INDEX IF NOT EXISTS idx_notif_pref_tenant ON notification_preferences (tenant_id);
CREATE INDEX IF NOT EXISTS idx_notif_pref_user ON notification_preferences (user_id);
CREATE INDEX IF NOT EXISTS idx_notif_pref_type ON notification_preferences (notification_type);
