CREATE TABLE IF NOT EXISTS notification_delivery_attempts (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id         BIGINT NOT NULL,
    notification_id   BIGINT NOT NULL,
    correlation_id    VARCHAR(100) NOT NULL,
    channel           VARCHAR(50) NOT NULL,
    status            VARCHAR(50) NOT NULL,
    attempt_number    INT NOT NULL,
    provider          VARCHAR(50),
    provider_response TEXT,
    error_message     TEXT,
    started_at        TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    completed_at      TIMESTAMP(6) WITH TIME ZONE,
    duration_ms       BIGINT,
    next_retry_at     TIMESTAMP(6) WITH TIME ZONE,
    created_at        TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at        TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_by        VARCHAR(255),
    updated_by        VARCHAR(255),
    version           BIGINT NOT NULL DEFAULT 0,
    deleted           BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at        TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT pk_notification_delivery_attempts PRIMARY KEY (id),
    CONSTRAINT fk_delivery_attempts_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_delivery_attempts_notification FOREIGN KEY (notification_id) REFERENCES notifications(id)
);

CREATE INDEX IF NOT EXISTS idx_deliv_att_notif ON notification_delivery_attempts (notification_id);
CREATE INDEX IF NOT EXISTS idx_deliv_att_corr ON notification_delivery_attempts (correlation_id);
CREATE INDEX IF NOT EXISTS idx_deliv_att_status ON notification_delivery_attempts (status);
CREATE INDEX IF NOT EXISTS idx_deliv_att_channel ON notification_delivery_attempts (channel);
CREATE INDEX IF NOT EXISTS idx_deliv_att_tenant ON notification_delivery_attempts (tenant_id);
