-- ==========================================================================
-- V2__initial_schema.sql
-- ForumX initial database schema
-- Generated from JPA entities under com.forumx.auth.entity and
-- com.forumx.tenant.entity (extending com.forumx.common.entity.BaseEntity)
-- Uses IF NOT EXISTS to be safely re-runnable against partial state.
-- ==========================================================================

-- ── Drop stale tables from previous incomplete migrations ───────────────────
-- The previous V1 migration may have created tables with a schema that
-- does not match the current JPA model. Drop them so we can recreate cleanly.

drop table if exists refresh_tokens cascade;
drop table if exists role_permissions cascade;
drop table if exists user_roles cascade;
drop table if exists user_profiles cascade;
drop table if exists permissions cascade;
drop table if exists roles cascade;
drop table if exists users cascade;
drop table if exists tenants cascade;

-- ── tenants ─────────────────────────────────────────────────────────────────

create table tenants (
    id                bigint generated by default as identity not null,
    created_at        timestamp(6) with time zone not null,
    updated_at        timestamp(6) with time zone not null,
    created_by        varchar(255),
    updated_by        varchar(255),
    version           bigint not null,
    deleted           boolean not null,
    deleted_at        timestamp(6) with time zone,
    name              varchar(100) not null,
    slug              varchar(100) not null,
    description       varchar(500),
    logo_url          varchar(500),
    website           varchar(255),
    contact_email     varchar(255),
    contact_phone     varchar(30),
    status            varchar(20) not null,
    subscription_plan varchar(20) not null,
    max_users         integer not null,
    storage_quota_mb  bigint not null,
    timezone          varchar(50),
    locale            varchar(10),
    primary key (id)
);

alter table tenants add constraint uk_tenants_name unique (name);
alter table tenants add constraint uk_tenants_slug unique (slug);

create index idx_tenants_status on tenants (status);
create index idx_tenants_subscription_plan on tenants (subscription_plan);

-- ── users ───────────────────────────────────────────────────────────────────

create table users (
    id                      bigint generated by default as identity not null,
    created_at              timestamp(6) with time zone not null,
    updated_at              timestamp(6) with time zone not null,
    created_by              varchar(255),
    updated_by              varchar(255),
    version                 bigint not null,
    deleted                 boolean not null,
    deleted_at              timestamp(6) with time zone,
    tenant_id               bigint not null,
    username                varchar(50) not null,
    email                   varchar(255) not null,
    password_hash           varchar(255) not null,
    phone_number            varchar(30),
    status                  varchar(20) not null,
    email_verified          boolean not null,
    account_locked          boolean not null,
    account_expired         boolean not null,
    credentials_expired     boolean not null,
    enabled                 boolean not null,
    last_login_at           timestamp(6) with time zone,
    last_password_change_at timestamp(6) with time zone,
    failed_login_attempts   integer not null,
    primary key (id)
);

alter table users add constraint uk_users_tenant_username unique (tenant_id, username);
alter table users add constraint uk_users_tenant_email unique (tenant_id, email);
alter table users add constraint fk_users_tenant foreign key (tenant_id) references tenants;

create index idx_users_tenant_id on users (tenant_id);
create index idx_users_username on users (username);
create index idx_users_email on users (email);
create index idx_users_status on users (status);
create index idx_users_enabled on users (enabled);

-- ── user_profiles ───────────────────────────────────────────────────────────

create table user_profiles (
    id                      bigint generated by default as identity not null,
    created_at              timestamp(6) with time zone not null,
    updated_at              timestamp(6) with time zone not null,
    created_by              varchar(255),
    updated_by              varchar(255),
    version                 bigint not null,
    deleted                 boolean not null,
    deleted_at              timestamp(6) with time zone,
    user_id                 bigint not null unique,
    first_name              varchar(100),
    last_name               varchar(100),
    display_name            varchar(100),
    bio                     varchar(2000),
    avatar_url              varchar(500),
    website                 varchar(255),
    github_url              varchar(255),
    linkedin_url            varchar(255),
    company                 varchar(150),
    department              varchar(100),
    job_title               varchar(100),
    location                varchar(150),
    timezone                varchar(50),
    locale                  varchar(10),
    date_of_birth           date,
    gender                  varchar(20),
    preferred_language      varchar(10),
    theme_preference        varchar(10) not null,
    notification_preference varchar(20) not null,
    primary key (id)
);

alter table user_profiles add constraint fk_user_profiles_user foreign key (user_id) references users;

create index idx_user_profiles_user_id on user_profiles (user_id);
create index idx_user_profiles_display_name on user_profiles (display_name);
create index idx_user_profiles_location on user_profiles (location);
create index idx_user_profiles_company on user_profiles (company);

-- ── roles ───────────────────────────────────────────────────────────────────

create table roles (
    id          bigint generated by default as identity not null,
    created_at  timestamp(6) with time zone not null,
    updated_at  timestamp(6) with time zone not null,
    created_by  varchar(255),
    updated_by  varchar(255),
    version     bigint not null,
    deleted     boolean not null,
    deleted_at  timestamp(6) with time zone,
    role_name   varchar(50) not null,
    description varchar(255),
    active      boolean not null,
    primary key (id)
);

alter table roles add constraint uk_roles_role_name unique (role_name);

create index idx_roles_role_name on roles (role_name);
create index idx_roles_active on roles (active);

-- ── permissions ─────────────────────────────────────────────────────────────

create table permissions (
    id              bigint generated by default as identity not null,
    created_at      timestamp(6) with time zone not null,
    updated_at      timestamp(6) with time zone not null,
    created_by      varchar(255),
    updated_by      varchar(255),
    version         bigint not null,
    deleted         boolean not null,
    deleted_at      timestamp(6) with time zone,
    permission_code varchar(100) not null,
    display_name    varchar(150),
    description     varchar(500),
    module          varchar(100),
    active          boolean not null,
    primary key (id)
);

alter table permissions add constraint uk_permissions_permission_code unique (permission_code);

create index idx_permissions_permission_code on permissions (permission_code);
create index idx_permissions_module on permissions (module);
create index idx_permissions_active on permissions (active);

-- ── user_roles ──────────────────────────────────────────────────────────────

create table user_roles (
    id                  bigint generated by default as identity not null,
    created_at          timestamp(6) with time zone not null,
    updated_at          timestamp(6) with time zone not null,
    created_by          varchar(255),
    updated_by          varchar(255),
    version             bigint not null,
    deleted             boolean not null,
    deleted_at          timestamp(6) with time zone,
    user_id             bigint not null,
    role_id             bigint not null,
    assigned_by_user_id bigint,
    expires_at          timestamp(6) with time zone,
    active              boolean not null,
    primary key (id)
);

alter table user_roles add constraint uk_user_roles_user_role unique (user_id, role_id);
alter table user_roles add constraint fk_user_roles_user foreign key (user_id) references users;
alter table user_roles add constraint fk_user_roles_role foreign key (role_id) references roles;

create index idx_user_roles_user on user_roles (user_id);
create index idx_user_roles_role on user_roles (role_id);
create index idx_user_roles_active on user_roles (active);
create index idx_user_roles_expires_at on user_roles (expires_at);
create index idx_user_roles_user_active on user_roles (user_id, active);

-- ── role_permissions ────────────────────────────────────────────────────────

create table role_permissions (
    id            bigint generated by default as identity not null,
    created_at    timestamp(6) with time zone not null,
    updated_at    timestamp(6) with time zone not null,
    created_by    varchar(255),
    updated_by    varchar(255),
    version       bigint not null,
    deleted       boolean not null,
    deleted_at    timestamp(6) with time zone,
    role_id       bigint not null,
    permission_id bigint not null,
    granted_by    varchar(255),
    granted_at    timestamp(6) with time zone,
    active        boolean not null,
    primary key (id)
);

alter table role_permissions add constraint uk_role_permissions_role_id_permission_id unique (role_id, permission_id);
alter table role_permissions add constraint fk_role_permissions_role foreign key (role_id) references roles;
alter table role_permissions add constraint fk_role_permissions_permission foreign key (permission_id) references permissions;

create index idx_role_permissions_role_id on role_permissions (role_id);
create index idx_role_permissions_permission_id on role_permissions (permission_id);
create index idx_role_permissions_active on role_permissions (active);

-- ── refresh_tokens ──────────────────────────────────────────────────────────

create table refresh_tokens (
    id           bigint generated by default as identity not null,
    created_at   timestamp(6) with time zone not null,
    updated_at   timestamp(6) with time zone not null,
    created_by   varchar(255),
    updated_by   varchar(255),
    version      bigint not null,
    deleted      boolean not null,
    deleted_at   timestamp(6) with time zone,
    user_id      bigint not null,
    token        varchar(500) not null,
    device_id    varchar(255),
    device_name  varchar(255),
    ip_address   varchar(45),
    user_agent   varchar(500),
    expires_at   timestamp(6) with time zone not null,
    revoked      boolean not null,
    revoked_at   timestamp(6) with time zone,
    last_used_at timestamp(6) with time zone,
    primary key (id)
);

alter table refresh_tokens add constraint uk_refresh_tokens_token unique (token);
alter table refresh_tokens add constraint fk_refresh_tokens_user foreign key (user_id) references users;

create index idx_refresh_tokens_user_id on refresh_tokens (user_id);
create index idx_refresh_tokens_token on refresh_tokens (token);
create index idx_refresh_tokens_expires_at on refresh_tokens (expires_at);
create index idx_refresh_tokens_revoked on refresh_tokens (revoked);
