ALTER TABLE chat_sessions ALTER COLUMN moderator_id DROP NOT NULL;

CREATE TABLE IF NOT EXISTS support_session_participants (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    session_id  BIGINT NOT NULL,
    tenant_id   BIGINT NOT NULL,
    user_id     BIGINT NOT NULL,
    role        VARCHAR(30) NOT NULL,
    joined_at   TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    left_at     TIMESTAMP(6) WITH TIME ZONE,
    is_active   BOOLEAN NOT NULL DEFAULT TRUE,
    created_by  VARCHAR(255),
    updated_by  VARCHAR(255),
    version     BIGINT NOT NULL DEFAULT 0,
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    deleted     BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at  TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT pk_support_session_participants PRIMARY KEY (id),
    CONSTRAINT fk_participants_session FOREIGN KEY (session_id) REFERENCES chat_sessions(id),
    CONSTRAINT fk_participants_tenant  FOREIGN KEY (tenant_id)  REFERENCES tenants(id),
    CONSTRAINT fk_participants_user    FOREIGN KEY (user_id)    REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_participants_session_active ON support_session_participants (session_id, is_active);
CREATE INDEX IF NOT EXISTS idx_participants_user_session   ON support_session_participants (user_id, session_id);
CREATE INDEX IF NOT EXISTS idx_participants_tenant         ON support_session_participants (tenant_id);
