-- ==========================================================================
-- V37__create_tenant_admin_invitations.sql
-- ==========================================================================
-- Migration to create the tenant_admin_invitations table for platform-driven tenant admin onboarding.
-- Stores cryptographically hashed tokens, expiration, status, and tenant binding.
-- ==========================================================================

create table if not exists tenant_admin_invitations (
    id                  bigint generated by default as identity not null,
    created_at          timestamp(6) with time zone not null,
    updated_at          timestamp(6) with time zone not null,
    created_by          varchar(255),
    updated_by          varchar(255),
    version             bigint not null,
    deleted             boolean not null default false,
    deleted_at          timestamp(6) with time zone,

    tenant_id           bigint not null,
    email               varchar(255) not null,
    role                varchar(50) not null,
    token_hash          varchar(255) not null,
    invited_by_user_id  bigint not null,
    status              varchar(20) not null,
    expires_at          timestamp(6) with time zone not null,
    accepted_at         timestamp(6) with time zone,
    revoked_at          timestamp(6) with time zone,

    primary key (id),
    constraint uk_tenant_admin_invitations_token_hash unique (token_hash),
    constraint fk_tenant_admin_invitations_tenant foreign key (tenant_id) references tenants(id),
    constraint fk_tenant_admin_invitations_invited_by foreign key (invited_by_user_id) references users(id)
);

create index if not exists idx_tenant_admin_invitations_tenant_id on tenant_admin_invitations (tenant_id);
create index if not exists idx_tenant_admin_invitations_token_hash on tenant_admin_invitations (token_hash);
create index if not exists idx_tenant_admin_invitations_tenant_status on tenant_admin_invitations (tenant_id, status);
create index if not exists idx_tenant_admin_invitations_tenant_email on tenant_admin_invitations (tenant_id, email);
create index if not exists idx_tenant_admin_invitations_expires_at on tenant_admin_invitations (expires_at);
