-- Flyway Migration: V38__create_question_views.sql
-- Description: Create the question_views table for unique per-user question view tracking.

CREATE TABLE IF NOT EXISTS question_views (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id         BIGINT NOT NULL,
    question_id       BIGINT NOT NULL,
    viewer_id         BIGINT NOT NULL,
    viewed_at         TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_at        TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at        TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_by        VARCHAR(255),
    updated_by        VARCHAR(255),
    version           BIGINT NOT NULL,
    deleted           BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at        TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT pk_question_views PRIMARY KEY (id),
    CONSTRAINT fk_question_views_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_question_views_question FOREIGN KEY (question_id) REFERENCES questions(id),
    CONSTRAINT fk_question_views_viewer FOREIGN KEY (viewer_id) REFERENCES users(id),
    CONSTRAINT uk_question_views_question_viewer UNIQUE (question_id, viewer_id)
);

CREATE INDEX IF NOT EXISTS idx_question_views_question ON question_views (question_id);
CREATE INDEX IF NOT EXISTS idx_question_views_viewer ON question_views (viewer_id);
CREATE INDEX IF NOT EXISTS idx_question_views_tenant ON question_views (tenant_id);
