-- ==========================================================================
-- V5__password_reset.sql
-- ==========================================================================

-- 1. Create password_reset_tokens table
CREATE TABLE IF NOT EXISTS password_reset_tokens (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at              TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at              TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_by              VARCHAR(255),
    updated_by              VARCHAR(255),
    version                 BIGINT NOT NULL,
    deleted                 BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at              TIMESTAMP(6) WITH TIME ZONE,
    user_id                 BIGINT NOT NULL,
    token_hash              VARCHAR(100) NOT NULL,
    expires_at              TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    used                    BOOLEAN NOT NULL DEFAULT FALSE,
    used_at                 TIMESTAMP(6) WITH TIME ZONE,
    PRIMARY KEY (id)
);

-- Add unique constraint on token_hash if it does not exist
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uk_password_reset_tokens_token_hash') THEN
        ALTER TABLE password_reset_tokens ADD CONSTRAINT uk_password_reset_tokens_token_hash UNIQUE (token_hash);
    END IF;
END $$;

-- Add foreign key constraint to users table with ON DELETE CASCADE if it does not exist
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_password_reset_tokens_user') THEN
        ALTER TABLE password_reset_tokens ADD CONSTRAINT fk_password_reset_tokens_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
    END IF;
END $$;

-- Add indexes if they don't exist
CREATE INDEX IF NOT EXISTS idx_password_reset_tokens_user_id ON password_reset_tokens (user_id);
CREATE INDEX IF NOT EXISTS idx_password_reset_tokens_token_hash ON password_reset_tokens (token_hash);
CREATE INDEX IF NOT EXISTS idx_password_reset_tokens_expires_at ON password_reset_tokens (expires_at);
